export const menuData = [
  {
    'ID': 1081,
    'post_author': '1',
    'post_date': '2019-07-02 20:00:13',
    'post_date_gmt': '2019-07-02 20:00:13',
    'post_content': '',
    'post_title': 'Privacy Policy',
    'post_excerpt': '',
    'post_status': 'publish',
    'comment_status': 'closed',
    'ping_status': 'closed',
    'post_password': '',
    'post_name': 'privacy-policy',
    'to_ping': '',
    'pinged': '',
    'post_modified': '2019-07-13 21:20:51',
    'post_modified_gmt': '2019-07-13 21:20:51',
    'post_content_filtered': '',
    'post_parent': 0,
    'guid': 'http://localhost:3200/privacy-policy/',
    'menu_order': 1,
    'post_type': 'nav_menu_item',
    'post_mime_type': '',
    'comment_count': '0',
    'filter': 'raw',
    'db_id': 1081,
    'menu_item_parent': '0',
    'object_id': '3',
    'object': 'page',
    'type': 'page',
    'type_label': 'Custom Link',
    'title': 'Privacy Policy',
    'url': '',
    'target': '',
    'attr_title': '',
    'description': '',
    'classes': ['1'],
    'xfn': ''
  },
  {
    'ID': 1093,
    'post_author': '1',
    'post_date': '2019-07-02 20:29:00',
    'post_date_gmt': '2019-07-02 20:29:00',
    'post_content': '',
    'post_title': 'My Custom Page',
    'post_excerpt': '',
    'post_status': 'publish',
    'comment_status': 'closed',
    'ping_status': 'closed',
    'post_password': '',
    'post_name': 'my-custom-page',
    'to_ping': '',
    'pinged': '',
    'post_modified': '2019-07-13 21:20:51',
    'post_modified_gmt': '2019-07-13 21:20:51',
    'post_content_filtered': '',
    'post_parent': 0,
    'guid': 'http://localhost:3200/my-custom-page/',
    'menu_order': 2,
    'post_type': 'nav_menu_item',
    'post_mime_type': '',
    'comment_count': '0',
    'filter': 'raw',
    'db_id': 1093,
    'menu_item_parent': '1081',
    'object_id': '153',
    'object': 'custom_page',
    'type': 'custom_page',
    'type_label': 'Custom Link',
    'title': 'My Custom Page',
    'url': '',
    'target': '',
    'attr_title': '',
    'description': '',
    'classes': ['1'],
    'xfn': ''
  },
  {
    'ID': 1084,
    'post_author': '1',
    'post_date': '2019-07-02 20:00:13',
    'post_date_gmt': '2019-07-02 20:00:13',
    'post_content': '',
    'post_title': 'Some Other Page',
    'post_excerpt': '',
    'post_status': 'publish',
    'comment_status': 'closed',
    'ping_status': 'closed',
    'post_password': '',
    'post_name': 'some-other-page',
    'to_ping': '',
    'pinged': '',
    'post_modified': '2019-07-13 21:20:51',
    'post_modified_gmt': '2019-07-13 21:20:51',
    'post_content_filtered': '',
    'post_parent': 0,
    'guid': 'http://localhost:3200/some-other-page/',
    'menu_order': 3,
    'post_type': 'nav_menu_item',
    'post_mime_type': '',
    'comment_count': '0',
    'filter': 'raw',
    'db_id': 1084,
    'menu_item_parent': '0',
    'object_id': '26',
    'object': 'page',
    'type': 'page',
    'type_label': 'Custom Link',
    'title': 'Some Other Page',
    'url': '',
    'target': '',
    'attr_title': '',
    'description': '',
    'classes': ['1'],
    'xfn': ''
  },
  {
    'ID': 1082,
    'post_author': '1',
    'post_date': '2019-07-02 20:00:13',
    'post_date_gmt': '2019-07-02 20:00:13',
    'post_content': '',
    'post_title': 'Some Subpage',
    'post_excerpt': '',
    'post_status': 'publish',
    'comment_status': 'closed',
    'ping_status': 'closed',
    'post_password': '',
    'post_name': 'some-subpage',
    'to_ping': '',
    'pinged': '',
    'post_modified': '2019-07-13 21:20:51',
    'post_modified_gmt': '2019-07-13 21:20:51',
    'post_content_filtered': '',
    'post_parent': 0,
    'guid': 'http://localhost:3200/some-subpage/',
    'menu_order': 4,
    'post_type': 'nav_menu_item',
    'post_mime_type': '',
    'comment_count': '0',
    'filter': 'raw',
    'db_id': 1082,
    'menu_item_parent': '0',
    'object_id': '22',
    'object': 'page',
    'type': 'page',
    'type_label': 'Custom Link',
    'title': 'Some Subpage',
    'url': '',
    'target': '',
    'attr_title': '',
    'description': '',
    'classes': ['1'],
    'xfn': '' }, { 'ID': 1085,
    'post_author': '1',
    'post_date': '2019-07-02 20:00:13',
    'post_date_gmt': '2019-07-02 20:00:13',
    'post_content': '',
    'post_title': 'Some Another Page',
    'post_excerpt': '',
    'post_status': 'publish',
    'comment_status': 'closed',
    'ping_status': 'closed',
    'post_password': '',
    'post_name': 'some-another-page',
    'to_ping': '',
    'pinged': '',
    'post_modified': '2019-07-13 21:20:51',
    'post_modified_gmt': '2019-07-13 21:20:51',
    'post_content_filtered': '',
    'post_parent': 0,
    'guid': 'http://localhost:3200/some-another-page/',
    'menu_order': 5,
    'post_type': 'nav_menu_item',
    'post_mime_type': '',
    'comment_count': '0',
    'filter': 'raw',
    'db_id': 1085,
    'menu_item_parent': '0',
    'object_id': '28',
    'object': 'page',
    'type': 'page',
    'type_label': 'Custom Link',
    'title': 'Some Another Page',
    'url': '',
    'target': '',
    'attr_title': '',
    'description': '',
    'classes': ['1'],
    'xfn': '' }, { 'ID': 1083,
    'post_author': '1',
    'post_date': '2019-07-02 20:00:13',
    'post_date_gmt': '2019-07-02 20:00:13',
    'post_content': '',
    'post_title': 'Some SubSubpage',
    'post_excerpt': '',
    'post_status': 'publish',
    'comment_status': 'closed',
    'ping_status': 'closed',
    'post_password': '',
    'post_name': 'some-subsubpage',
    'to_ping': '',
    'pinged': '',
    'post_modified': '2019-07-13 21:20:51',
    'post_modified_gmt': '2019-07-13 21:20:51',
    'post_content_filtered': '',
    'post_parent': 0,
    'guid': 'http://localhost:3200/some-subsubpage/',
    'menu_order': 6,
    'post_type': 'nav_menu_item',
    'post_mime_type': '',
    'comment_count': '0',
    'filter': 'raw',
    'db_id': 1083,
    'menu_item_parent': '0',
    'object_id': '24',
    'object': 'page',
    'type': 'page',
    'type_label': 'Custom Link',
    'title': 'Some SubSubpage',
    'url': '',
    'target': '',
    'attr_title': '',
    'description': '',
    'classes': ['1'],
    'xfn': ''
  }
]

export default menuData
